# Generated by Django 6.0.3 on 2026-05-29 20:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insumo',
            name='modificado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_maximo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='HistorialStockInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MANUAL', 'Ajuste manual'), ('COMPRA', 'Entrada por compra')], default='MANUAL', max_length=10)),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('motivo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_stock', to='insumos.insumo')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_stock_insumo_realizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de stock de insumo',
                'verbose_name_plural': 'Historial de stock de insumos',
                'db_table': 'historial_stock_insumo',
                'ordering': ['-fecha'],
            },
        ),
    ]
