# Generated by Django 6.0.3 on 2026-05-29 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cliente_creado_por_cliente_modificado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('USUARIO', 'Usuario'), ('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], max_length=20)),
                ('objeto_id', models.IntegerField()),
                ('objeto_nombre', models.CharField(max_length=200)),
                ('accion', models.CharField(choices=[('EDITAR', 'Editar'), ('ACTIVAR', 'Activar'), ('DESACTIVAR', 'Desactivar')], max_length=20)),
                ('observacion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cambios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de cambio',
                'verbose_name_plural': 'Historial de cambios',
                'db_table': 'historial_cambio',
                'ordering': ['-fecha'],
            },
        ),
    ]
