# Generated by Django 6.0.3 on 2026-04-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
        ),
    ]
